name: Run CSV Validation

on: [push]  # Bisa diatur untuk event lain seperti pull_request, schedule, dll.

jobs:
  validate-csv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # Checkout kode dari repository Anda

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      # Mengatur versi Python yang ingin digunakan

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
      # Menginstal dependensi yang diperlukan untuk skrip Python Anda

    - name: Run CSV validation script
      run: python comparison_report.py
      env:
        USER_SUPER_ADMIN: ${{ secrets.USER_SUPER_ADMIN }}
        PASS_SUPER_ADMIN: ${{ secrets.PASS_SUPER_ADMIN }}
      # Menjalankan skrip validasi CSV dan mengatur variabel lingkungan
