name: Run CSV Validation

on:
  push:  # Existing trigger for push events
  schedule:
    - cron: '00 22 * * *'  # 10 PM UTC (5 AM WIB)
    - cron: '00 09 * * *'  # 9 AM UTC (4 PM WIB)
    
jobs:
  validate-csv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # Checkout kode dari repository Anda

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      # Mengatur versi Python yang ingin digunakan

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
#        pip install -r requirements.txt  # Assumes you have a requirements.txt file
      # Menginstal dependensi yang diperlukan untuk skrip Python Anda

    - name: Run CSV validation script
      run: python main.py
      env:
        USER_SUPER_ADMIN: ${{ secrets.USER_SUPER_ADMIN }}
        PASS_SUPER_ADMIN: ${{ secrets.PASS_SUPER_ADMIN }}
    
    - name: Check for validation errors
      run: |
        if [ -f "validation_error.txt" ]; then
          echo "Validation failed. See validation_error.txt for details."
          exit  1
        fi
        
    - name: List directory contents
      run: ls -la
